[package]
name = "content-aware-image-resizer"
version = "0.1.0"
authors = ["Yanglin Zhao <yz1876@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
