name: Main Workflow

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: which node && node --version
      - run: which yarn && yarn --version
      - run: yarn install
      - run: PUBLIC_URL="/rust-wasm-seam-carving/" yarn build
